/**
 */
package ecore.org.cocome.tradingsystem.inventory.data.store.provider;

import ecore.org.cocome.tradingsystem.inventory.data.store.util.StoreAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class StoreItemProviderAdapterFactory extends StoreAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public StoreItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ecore.org.cocome.tradingsystem.inventory.data.store.EnterpriseStoreQueryProvider} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnterpriseStoreQueryProviderItemProvider enterpriseStoreQueryProviderItemProvider;

	/**
	 * This creates an adapter for a {@link ecore.org.cocome.tradingsystem.inventory.data.store.EnterpriseStoreQueryProvider}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnterpriseStoreQueryProviderAdapter() {
		if (enterpriseStoreQueryProviderItemProvider == null) {
			enterpriseStoreQueryProviderItemProvider = new EnterpriseStoreQueryProviderItemProvider(this);
		}

		return enterpriseStoreQueryProviderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ecore.org.cocome.tradingsystem.inventory.data.store.OrderEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrderEntryItemProvider orderEntryItemProvider;

	/**
	 * This creates an adapter for a {@link ecore.org.cocome.tradingsystem.inventory.data.store.OrderEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrderEntryAdapter() {
		if (orderEntryItemProvider == null) {
			orderEntryItemProvider = new OrderEntryItemProvider(this);
		}

		return orderEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ecore.org.cocome.tradingsystem.inventory.data.store.ProductOrder} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductOrderItemProvider productOrderItemProvider;

	/**
	 * This creates an adapter for a {@link ecore.org.cocome.tradingsystem.inventory.data.store.ProductOrder}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProductOrderAdapter() {
		if (productOrderItemProvider == null) {
			productOrderItemProvider = new ProductOrderItemProvider(this);
		}

		return productOrderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ecore.org.cocome.tradingsystem.inventory.data.store.StockItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StockItemItemProvider stockItemItemProvider;

	/**
	 * This creates an adapter for a {@link ecore.org.cocome.tradingsystem.inventory.data.store.StockItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStockItemAdapter() {
		if (stockItemItemProvider == null) {
			stockItemItemProvider = new StockItemItemProvider(this);
		}

		return stockItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ecore.org.cocome.tradingsystem.inventory.data.store.Store} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StoreItemProvider storeItemProvider;

	/**
	 * This creates an adapter for a {@link ecore.org.cocome.tradingsystem.inventory.data.store.Store}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStoreAdapter() {
		if (storeItemProvider == null) {
			storeItemProvider = new StoreItemProvider(this);
		}

		return storeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ecore.org.cocome.tradingsystem.inventory.data.store.StoreDatatypesFactory} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StoreDatatypesFactoryItemProvider storeDatatypesFactoryItemProvider;

	/**
	 * This creates an adapter for a {@link ecore.org.cocome.tradingsystem.inventory.data.store.StoreDatatypesFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStoreDatatypesFactoryAdapter() {
		if (storeDatatypesFactoryItemProvider == null) {
			storeDatatypesFactoryItemProvider = new StoreDatatypesFactoryItemProvider(this);
		}

		return storeDatatypesFactoryItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (enterpriseStoreQueryProviderItemProvider != null) enterpriseStoreQueryProviderItemProvider.dispose();
		if (orderEntryItemProvider != null) orderEntryItemProvider.dispose();
		if (productOrderItemProvider != null) productOrderItemProvider.dispose();
		if (stockItemItemProvider != null) stockItemItemProvider.dispose();
		if (storeItemProvider != null) storeItemProvider.dispose();
		if (storeDatatypesFactoryItemProvider != null) storeDatatypesFactoryItemProvider.dispose();
	}

}
